export const DEFAULT_SPEC = {
    "name": "Narrative System",
    "role": "Personal Transformation Storytelling Director",
    "tags": [],
    "task": "Plan and write a complete YouTube video script based on the provided subject and target duration. The script must include narration, character actions, emotional states, visual composition and transitions.",
    "goals": [
        "Create a powerful hook within the first 10 seconds",
        "Explain psychological ideas through concrete everyday situations",
        "Maintain an emotional tension arc (rise → peak → reflection → final insight)",
        "Keep strong visual storytelling through character actions",
        "Deliver a memorable and cinematic ending"
    ],
    "rules": [
        "TOTAL VIDEO DURATION MUST NOT exceed the requested duration.",
        "Aim for 10-12 seconds per scene.",
        "Narration MUST be complete, logically coherent sentences. Never cut mid-sentence — rewrite long sentences into shorter ones.",
        "Each scene narration MUST be a verbatim slice of 'fullNarration'.",
        "Transitions MUST occur at natural pauses (full stops, commas, breath marks).",
        "Max 1–2 speaking characters per scene. Speaking → slow zoom-in + lip movement. After → slow zoom-out.",
        "No abrupt motion. Split complex actions across multiple scenes (3-8s per visual cut).",
        "Recurring characters use consistent IDs (CHAR-01, CHAR-02, etc.).",
        "ACTIONS: clean visual descriptions only. No timing tags, no video keywords, no appearance descriptions.",
        "ANIMATION PROMPT: contains all timing tags and movement instructions.",
        "Avoid clichés. Prefer concrete daily-life situations.",
        "poseId: use library poses (STAND, WALK, RUN, THINK, POINT, SAD, JUMP, SIT, TYPE, EXHAUSTED, NOTEBOOK, PHONE, ANGRY, SHOCK, MEDITATE, LOOK-BACK, CARRY-BOX, FALL, NONE) or propose new descriptive names — system will auto-generate unknown poses.",
        "poseStyle: position (left/center/right), scale (0.5–1.5). Use left/right when onscreenText is present to avoid overlap.",
        "onscreenTextSuggestions: 3-5 variations — vary wording, tone, and positioning (top/bottom/center).",
        "OUTPUT MUST BE STRICTLY VALID JSON."
    ],
    "context": "Cinematic director specialized in psychological storytelling. The goal is to produce emotionally engaging scripts with strong pacing, clear psychological insight, and visually driven storytelling.",
    "category": "Storytelling",
    "structure": "Hook -> Problem -> Exploration -> Psychological Insight -> Practical Shift -> Conclusion",
    "formatting": "Each scene must include narration, character actions, expression, duration, timestamp, summary, characterIds, speechBubble, mood, cameraType, framing, lighting, and animation prompt. Include anchorDetail for grounding.",
    "instructions": [
        "Think step-by-step.",
        "First, write the complete narration in 'fullNarration'.",
        "Then, break it down into scenes.",
        "Ensure narration flows perfectly across cuts."
    ],
    outputFormat: JSON.stringify(
        {
            // ─── Story Identity ────────────────────────────────────────────────
            //storyGenre: 'thriller | drama | mystery | fable | horror-lite | romance | adventure',
            //logline: 'One sentence describing the story: who wants what, what stands in the way, what is at stake.',
            //twistScene: 'Integer — sceneNumber where the main narrative reversal occurs',
            //seedDetail: 'String — describe the planted clue or visual detail that foreshadows the twist',
            emotionalArc: ['Cold Open: unease', 'Rising: dread', 'Peak: despair', 'Twist: shock', 'Resolution: quiet clarity'],

            // ─── Standard fields ───────────────────────────────────────────────
            titles: ['Title 1', 'Title 2', 'Title 3'],
            fullNarration: 'String - The complete unbroken voice-over narration of the story.',
            topic: 'String',
            audience: 'String',
            characterSheets: [
                {
                    id: 'CHAR-01',
                    name: 'Name',
                    role: 'Role in the story',
                    secret: 'What this character hides',
                    want: 'What this character wants (surface)',
                    wound: 'What this character carries (deep)',
                    metadata: { gender: 'male|female|unknown', age: 'child|youth|senior|unknown' },
                    appearance: {
                        description: 'Base style',
                        clothing: 'Specific clothing...',
                        accessories: 'Distinguishing items',
                        colorPalette: ['#HEX1', '#HEX2'],
                        uniqueIdentifiers: ['Specific trait 1', 'Specific trait 2'],
                    },
                    expressions: ['Suspicious', 'Broken', 'Determined'],
                    imagePrompt: 'Consistent visual reference prompt',
                },
            ],
            scenes: [
                {
                    sceneNumber: 'Integer',
                    timeRange: { start: 'Float', end: 'Float' },
                    locationId: 'String - Identifier to reuse locations across scenes',
                    duration: 'Float',
                    timestamp: 'Float',
                    summary: 'String — what this scene does for the story',
                    narration: 'String',
                    actions: ['String'],
                    expression: 'String',
                    characterIds: ['String'],
                    speechBubble: 'String — real, imperfect, loaded dialogue or internal thought',
                    mood: 'String',
                    cameraType: 'String',
                    framing: 'String',
                    background: 'String - Explicit background description including weather and time-of-day',
                    lighting: 'String - Explicit lighting description (e.g., morning sun, neon, soft)',
                    props: ['String - Relevant props for this scene to track logically'],
                    imagePrompt: '[action/metaphor]',
                    animationPrompt: '...',

                    transitionToNext: 'fade | slide-left | zoom-in | wipe | swish | hard-cut',
                    tension: 5,
                    characterVariant: 'Optional character skin name',
                    continueFromPrevious: false,
                    visualSource: 'local',
                    poseId: 'NONE | STAND | WALK | RUN | TYPE | EXHAUSTED | ...',
                    poseStyle: {
                        position: 'left | center | right | custom',
                        x: 50,
                        y: 50,
                        scale: 1,
                    },
                    onscreenText: 'The primary large overlay text — used sparingly for impact',
                    onscreenTextSuggestions: [
                        'Concise version',
                        'Action-oriented version',
                        'Question-based version',
                        'Keyword-heavy version',
                    ],
                    onscreenTextStyle: {
                        enabled: true,
                        color: '#000000',
                        fontFamily: 'sans-serif',
                        fontSize: 58,
                        fontWeight: 'bold',
                        maxWordsPerLine: 6,
                        highlightWords: [{ word: 'specificword', color: '#FF0000' }],
                    },
                    anchorDetail: 'String — grounding physical or environmental detail',
                    soundEffects: [{ type: 'pop | whoosh | swish | ding | jump | heartbeat | rain | silence', timestamp: 1.5, volume: 0.8 }],
                    soundscape: 'String — ambient atmosphere description',
                },
            ],
        },
        null,
        2
    )
};