"use client";

import { Play } from "lucide-react";

const videos = [
  {
    title: "The 3 rules of wealth",
    niche: "Finance",
    duration: "4:12",
  },
  {
    title: "How dopamine controls you",
    niche: "Psychology",
    duration: "6:45",
  },
  {
    title: "Deep work framework",
    niche: "Productivity",
    duration: "5:30",
  },
  {
    title: "The fall of Rome",
    niche: "History",
    duration: "8:15",
  },
];

export function GallerySection() {
  return (
    <section className="py-32 bg-zinc-50 border-t border-zinc-100" id="gallery">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="text-center mb-20">
          <h2 className="text-sm font-black uppercase tracking-[0.4em] text-amber-500 mb-4">
            Gallery
          </h2>
          <h3 className="text-4xl md:text-5xl font-heading font-extrabold text-zinc-950">
            Real videos, generated by Sketch Pilot.
          </h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {videos.map((video, index) => (
            <div key={index} className="group relative rounded-3xl bg-white border border-zinc-200 overflow-hidden shadow-sm hover:shadow-xl transition-all hover:-translate-y-1">
              <div className="aspect-[9/16] bg-zinc-100 relative">
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent z-10" />
                <div className="absolute inset-0 flex items-center justify-center z-20">
                  <div className="h-12 w-12 rounded-full bg-white/20 backdrop-blur-md flex items-center justify-center text-white scale-90 group-hover:scale-110 group-hover:bg-amber-500 transition-all cursor-pointer">
                    <Play className="h-5 w-5 fill-current ml-1" />
                  </div>
                </div>
                <div className="absolute bottom-4 left-4 right-4 z-20">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-[10px] font-bold uppercase tracking-wider text-amber-400 bg-amber-500/20 px-2 py-0.5 rounded-full backdrop-blur-sm border border-amber-500/30">
                      {video.niche}
                    </span>
                    <span className="text-[10px] font-bold text-white/80">
                      {video.duration}
                    </span>
                  </div>
                  <h4 className="text-lg font-heading font-bold text-white leading-tight">
                    {video.title}
                  </h4>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
